# Define a 'Service' To Expose MySQL to Other Services
apiVersion: v1
kind: Service
metadata:
  name: accountDB
  labels:
    app: accountDB
    tier: database
spec:
  ports:
    - port: 3307
      targetPort: 3307
  selector:
    app: accountDB
    tier: database
  clusterIP: None # DNS is used, so clusterIP is not needed

---
# Define a 'Persistent Volume Claim'(PVC) for MySQL Storage, dynamically provisioned by cluster
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: accountDB-pv-claim # name of PVC essential for identifying the storage data
  labels:
    app: accountDB
    tier: database
spec:
  accessModes:
    - ReadWriteOnce   #This specifies the mode of the claim that we are trying to create.
  resources:
    requests:
      storage: 100Mi    #This will tell kubernetes about the amount of space we are trying to claim.

---
# Deployment specification begins here
apiVersion: apps/v1
kind: Deployment
metadata:
  name: accountDB
  labels:
    app: accountDB
    tier: database
spec:
  selector: # mySQL Pod Should contain same labels
    matchLabels:
      app: accountDB
  strategy:
    type: Recreate
  template:
    metadata:
      labels: # Must match 'Service' and 'Deployment' selectors
        app: accountDB
        tier: database
    spec:
      containers:
        - name: accountDB
          image: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: account
          ports:
            - containerPort: 3307
              name: mysql
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-accountDB-storage
      volumes:
        - name: mysql-accountDB-storage
          persistentVolumeClaim:
            claimName: accountDB-pv-claim
