---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-deployment
spec:
  selector:
    matchLabels:
      app: account
  replicas: 2
  template:
    metadata:
      labels:
        app: account
    spec:
      containers:
        - name: account
          image: leo/account
          ports:
            - containerPort: 9091
          env:
            - name: DB_HOST
              value: accountDB
            - name: DB_NAME
              value: account
            - name: DB_USERNAME
              value: root
            - name: DB_PASSWORD
              value: root
---
apiVersion: v1
kind: Service
metadata:
  name: Account-service
spec:
  ports:
    - protocol: "TCP"
      port: 9091
      targetPort: 9091
  selector:
    app: account
  type: NodePort